------------------
--[[ Configns ]]--
------------------

FRAMEWORK_CONFIGS["Templates"]["Levels"] = {
    baseEXP = 1000, expMultiplier = 1.2,

    ["Max_Level"] = 200,
    ["Ranks"] = {
        {name = "Novice", badge = 1},
        {name = "Apprentice", badge = 1},
        {name = "Journeyman", badge = 1},
        {name = "Pathfinder", badge = 1},
        {name = "Squire", badge = 1},
        {name = "Adventurer", badge = 1},
        {name = "Scout", badge = 1},
        {name = "Guardian", badge = 1},
        {name = "Fighter", badge = 1},
        {name = "Brawler", badge = 1},
        {name = "Scrapper", badge = 1},
        {name = "Brigand", badge = 1},
        {name = "Skirmisher", badge = 1},
        {name = "Battler", badge = 1},
        {name = "Marauder", badge = 1},
        {name = "Slayer", badge = 1},
        {name = "Huntsman", badge = 1},
        {name = "Mercenary", badge = 1},
        {name = "Swordsman", badge = 1},
        {name = "Freelancer", badge = 1},
        {name = "Swashbuckler", badge = 1},
        {name = "Vanquisher", badge = 1},
        {name = "Chevalier", badge = 1},
        {name = "Duelist", badge = 1},
        {name = "Gladiator", badge = 1},
        {name = "Legionnaire", badge = 1},
        {name = "Veteran", badge = 1},
        {name = "Swordmaster", badge = 1},
        {name = "Keeper", badge = 1},
        {name = "Protector", badge = 1},
        {name = "Defender", badge = 1},
        {name = "Warder", badge = 1},
        {name = "Gallant", badge = 1},
        {name = "Knight", badge = 1},
        {name = "Exemplar", badge = 1},
        {name = "Myrmidon", badge = 1},
        {name = "Conqueror", badge = 1},
        {name = "Lord", badge = 1},
        {name = "Paladin", badge = 1},
        {name = "Hero", badge = 1},
        {name = "Champion", badge = 1},
        {name = "Legend", badge = 1},
        {name = "Demigod", badge = 1},
        {name = "God", badge = 1}
    }
}