------------------
--[[ Configns ]]--
------------------

FRAMEWORK_CONFIGS["Templates"]["Levels"] = {
    baseEXP = 1000, expMultiplier = 1.2,

    ["Max_Level"] = 200,
    ["Ranks"] = {
        {name = "Novice", badge = 1},
        {name = "Apprentice", badge = 2},
        {name = "Journeyman", badge = 3},
        {name = "Pathfinder", badge = 4},
        {name = "Squire", badge = 5},
        {name = "Adventurer", badge = 6},
        {name = "Scout", badge = 7},
        {name = "Guardian", badge = 8},
        {name = "Fighter", badge = 9},
        {name = "Brawler", badge = 10},
        {name = "Scrapper", badge = 11},
        {name = "Brigand", badge = 12},
        {name = "Skirmisher", badge = 13},
        {name = "Battler", badge = 14},
        {name = "Marauder", badge = 15},
        {name = "Slayer", badge = 16},
        {name = "Huntsman", badge = 17},
        {name = "Mercenary", badge = 18},
        {name = "Swordsman", badge = 19},
        {name = "Freelancer", badge = 20},
        {name = "Swashbuckler", badge = 21},
        {name = "Vanquisher", badge = 22},
        {name = "Chevalier", badge = 22},
        {name = "Duelist", badge = 22},
        {name = "Gladiator", badge = 23},
        {name = "Legionnaire", badge = 23},
        {name = "Veteran", badge = 24},
        {name = "Swordmaster", badge = 24},
        {name = "Keeper", badge = 24},
        {name = "Protector", badge = 25},
        {name = "Defender", badge = 25},
        {name = "Warder", badge = 26},
        {name = "Gallant", badge = 26},
        {name = "Knight", badge = 27},
        {name = "Exemplar", badge = 27},
        {name = "Myrmidon", badge = 28},
        {name = "Conqueror", badge = 28},
        {name = "Lord", badge = 28},
        {name = "Paladin", badge = 28},
        {name = "Hero", badge = 29},
        {name = "Champion", badge = 29},
        {name = "Legend", badge = 29},
        {name = "Demigod", badge = 30},
        {name = "God", badge = 30}
    }
}