------------------
--[[ Configns ]]--
------------------

FRAMEWORK_CONFIGS["Templates"][""] = {
    baseEXP = 1000, expMultiplier = 1.2,

    ["Max_Level"] = 200,
    ["Ranks"] = {
        {name = "Novice"},
        {name = "Apprentice"},
        {name = "Journeyman"},
        {name = "Pathfinder"},
        {name = "Squire"},
        {name = "Adventurer"},
        {name = "Scout"},
        {name = "Guardian"},
        {name = "Fighter"},
        {name = "Brawler"},
        {name = "Scrapper"},
        {name = "Brigand"},
        {name = "Skirmisher"},
        {name = "Battler"},
        {name = "Marauder"},
        {name = "Slayer"},
        {name = "Huntsman"},
        {name = "Mercenary"},
        {name = "Swordsman"},
        {name = "Freelancer"},
        {name = "Swashbuckler"},
        {name = "Vanquisher"},
        {name = "Chevalier"},
        {name = "Duelist"},
        {name = "Gladiator"},
        {name = "Legionnaire"},
        {name = "Veteran"},
        {name = "Swordmaster"},
        {name = "Keeper"},
        {name = "Protector"},
        {name = "Defender"},
        {name = "Warder"},
        {name = "Gallant"},
        {name = "Knight"},
        {name = "Exemplar"},
        {name = "Myrmidon"},
        {name = "Conqueror"},
        {name = "Lord"},
        {name = "Paladin"},
        {name = "Hero"},
        {name = "Champion"},
        {name = "Legend"},
        {name = "Demigod"},
        {name = "God"}
    }
}